Feature: Install Tool
In order to setup TYPO3 properly
As a administrator using TYPO3
I want to create temporary files and set properties

Scenario: no install tool file generated by default
	pending
	When I run `file typo3conf/ENABLE_INSTALL_TOOL`
	Then the exit status should be 1
	And the output should contain "No such file or directory -- typo3conf/ENABLE_INSTALL_TOOL"

Scenario: Check that install tool is disabled by default
	pending
	Given I am on install-tool
	Then a file named "typo3conf/ENABLE_INSTALL_TOOL" should not exist

Scenario: Check enabled install tool
	pending
	Given I am on install-tool
	Then a file named "typo3conf/ENABLE_INSTALL_TOOL" should not exist

Scenario: Enabled install tool in backend
	pending
	Given I am a backend user
	And I go to my settings
	And I press "enable install tool"
	Then a file named "typo3conf/ENABLE_INSTALL_TOOL" should exist

Scenario: Disabled install tool in backend
	pending
	Given I am a backend user
	And I go to my settings
	And I press "disable install tool"
	Then a file named "typo3conf/ENABLE_INSTALL_TOOL" should not exist